version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - "./client/videos_dev:/root/videos"

  middleware:
    build:
      context: ./middleware
      dockerfile: middleware.dockerfile
    environment:
      - PYTHONUNBUFFERED=1