version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    image: rabbitmq
    ports:
      - 15672:15672
    networks:
      - testing_net
    container_name: rabbitmq
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10

  middleware:
    build:
      context: ./middleware
      dockerfile: middleware.dockerfile
    image: middleware
    container_name: middleware
    networks:
      - testing_net
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  ingestion_service:
    build:
      context: ./ingestion_service
      dockerfile: ingestion_service.dockerfile
    image: ingestion_service
    container_name: ingestion_service
    networks:
      - testing_net
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  like_filter:
    build:
      context: ./like_filter
      dockerfile: like_filter.dockerfile
    image: like_filter
    container_name: like_filter
    networks:
      - testing_net
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  funny_filter:
    build:
      context: ./funny_filter
      dockerfile: funny_filter.dockerfile
    image: funny_filter
    container_name: funny_filter
    networks:
      - testing_net
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  day_grouper:
    build:
      context: ./day_grouper
      dockerfile: day_grouper.dockerfile
    image: day_grouper
    container_name: day_grouper
    networks:
      - testing_net
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  reporting_service:
    build:
      context: ./reporting_service
      dockerfile: reporting_service.dockerfile
    image: reporting_service
    container_name: reporting_service
    networks:
      - testing_net
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

networks:
  testing_net:
    ipam:
      config:
        - subnet: 172.20.0.0/16