#MESSAGE IDS
SERVICE_MESSAGE_ID = 1

#CLIENT OPERATION IDS
START_PROCESS_OP_ID = 0
PROCESS_DATA_OP_ID = 1
END_PROCESS_OP_ID = 2
GET_RESULTS_OP_ID = 3

#SYSTEM WORKER IDS
INGEST_DATA_WORKER_ID = "ingestion_service"
LIKE_FILTER_WORKER_ID = "like_filter"
FUNNY_FILTER_WORKER_ID = "funny_filter"
STORAGE_DATA_WORKER_ID = "reporting_service"
