version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    image: rabbitmq
    ports:
      - 15672:15672
    networks:
      - testing_net
    container_name: rabbitmq
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10

  middleware:
    build:
      context: ./middleware
      dockerfile: middleware.dockerfile
    image: middleware
    container_name: middleware
    networks:
      - testing_net
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1